apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crud-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: crud.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crud-service
                port:
                  number: 80
